<?php
include_once $_SERVER["DOCUMENT_ROOT"] . '/checklogin.php';
include_once '../../api/models/Journals.php';

SharedManager::checkAuthToModule(35);
Journals::saveJournal('Accessing DTO Assembly Hours Page', PAGE_DTO_ASSEMBLY_HOURS, DTO_ASSEMBLY_HOURS_PANEL_BY, ACTION_VIEWED, null, 'DTO Assembly Hours Page Index');
SharedManager::saveLog('log_dtoconfigurator', 'Accessing DTO Assembly Hours Page');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DTO Configurator | DTO Assembly Hours</title>
    <?php include_once '../../partials/libraries.php'; ?>
    <link href="/dpm/dtoconfigurator/assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/dpm/dtoconfigurator/assets/css/dto-assembly-hours/style.css" rel="stylesheet" type="text/css"/>
</head>
<body>

<!-- Sidebar -->
<?php include_once '../../partials/sidebar.php'; ?>

<!-- Main Content Area -->
<div id="dtoAssemblyHoursPage" class="pusher" style="margin-right:260px;">
    <!-- Header -->
    <?php include_once '../../partials/header.php'; ?>

    <div class="ui active centered inline loader" style="margin-top:10%;"></div>

    <div class="dtoAssemblyHoursPageContainer ui container-fluid" style="padding-right:2%;">

        <div style="margin:0 auto;">
            <h3 class="ui header">
                <i class="clock icon"></i>
                <div class="content">
                    DTO Assembly Hours
                    <div class="sub header">This page provides information about the assembly times of DTOs.</div>
                </div>
            </h3>

            <div class="ui divider"></div>

            <!-- Tabular Menu -->
            <div class="ui top attached tabular menu">
                <div class="active item" data-tab="current-changes">
                    <i class="cube icon"></i>
                    Panel-Based Calculation
                </div>
                <div class="item" data-tab="planning">
                    <i class="cogs icon"></i>
                    Station-Based Calculation
                </div>
            </div>

            <!-- Current Changes Tab Content -->
            <div class="ui bottom attached active tab segment" data-tab="current-changes">
                <div class="ui form" style="margin-top:1.5rem;">
                    <div class="ui grid">
                        <div class="eight wide column">
                            <div class="field">
                                <h4 class="ui header" style="padding-left:4px;">Project Number</h4>
                                <select id="searchProjectSelect" name="searchProjectSelect" class="ui fluid selection search dropdown searchProjectSelect">
                                    <option value="">Search Project</option>
                                </select>
                            </div>
                        </div>
                        <div id="searchNachbauField" class="eight wide column" style="display:none;">
                            <div class="field">
                                <h4 class="ui header">Nachbau Number</h4>
                                <select id="searchNachbauSelect" name="searchNachbauSelect" class="ui fluid dropdown searchNachbauSelect">
                                    <option value="">Select Nachbau</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- DTO Assembly Hours Matrix Container -->
                <div id="dtoMatrixContainer" class="ui segment" style="display:none;">
                    <div class="ui active dimmer" style="display:none;">
                        <div class="ui large text loader">Loading DTO Assembly Hours Matrix...</div>
                    </div>
                    <div id="dtoAssemblyHoursTableContainer" class="table-responsive" style="overflow-x: auto;">
                        <table id="dtoAssemblyHoursTable" class="ui striped hover compact celled table stackable padded" style="width:100%">
                            <thead>
                            <!-- Dynamic headers will be generated by DataTable -->
                            </thead>
                            <tfoot>
                            <!-- Search inputs will be added here for filterable columns -->
                            </tfoot>
                            <tbody>
                            <!-- Data will be populated by DataTable -->
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Planning Tab Content -->
            <div class="ui bottom attached tab" data-tab="planning">
                <div style="margin-top: 2rem;">

                    <div class="ui form">
                        <div class="ui grid">
                            <div class="ten wide column">
                                <div class="field">
                                    <h4 class="ui header" style="padding-left:1px;">Project-Lot Numbers</h4>
                                    <textarea id="projectLotInput" style="font-size: 18px;font-weight: 700;color: red;" placeholder="Paste your project-lot numbers here&#10;Example:&#10;70240523-1&#10;70240523-2&#10;70240543-1" rows="8"></textarea>
                                    <div class="ui pointing top label" style="margin-top: 0.5rem;">
                                        <i class="info circle icon"></i>
                                        Format: ProjectNumber-LotNumber (one per line)
                                    </div>
                                </div>
                            </div>
                            <div class="six wide column">
                                <div class="field">
                                    <label>&nbsp;</label>
                                    <button id="parseBtn" class="ui labeled icon button blue fluid" style="margin-top: 0.2rem;">
                                        <i class="search icon"></i>
                                        Validate Projects
                                    </button>
                                    <button id="calculateBtn" class="ui labeled icon button green fluid" style="margin-top: 1rem;" disabled>
                                        <i class="calculator icon"></i>
                                        Calculate Hours
                                    </button>
                                    <button id="generateExcelBtn" class="ui labeled icon button orange fluid" style="margin-top: 1rem;" disabled>
                                        <i class="file excel icon"></i>
                                        Generate Excel
                                    </button>
                                    <button id="clearBtn" class="ui labeled icon button grey fluid" style="margin-top: 1rem;">
                                        <i class="eraser icon"></i>
                                        Clear All
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Parsed Results Table -->
                    <div id="parsedResultsContainer" class="ui segment" style="display:none; margin-top: 2rem;">
                        <h4 class="ui header">
                            <i class="table icon"></i>
                            Parsed Project-Lot Combinations
                        </h4>
                        <table id="parsedResultsTable" class="ui celled striped table">
                            <thead>
                            <tr>
                                <th>Project Number</th>
                                <th>Lot Number</th>
                                <th>Project Name</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            <!-- Parsed results will be populated here -->
                            </tbody>
                        </table>
                    </div>

                    <!-- Calculation Results Container -->
                    <div id="calculationResultsContainer" class="ui segment" style="display:none; margin-top: 2rem;">
                        <div class="ui large text loader" style="margin-top:1rem;display:none;">Calculating assembly hours...</div>
                        <h4 class="ui header" style="margin-top:0;">
                            <i class="chart bar icon"></i>
                            Assembly Hours Calculation Results
                        </h4>
                        <div id="calculationResultsContent"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<script src="/dpm/dtoconfigurator/assets/js/main.js?<?=uniqid()?>"></script>
<script src="/dpm/dtoconfigurator/assets/js/dto-assembly-hours/panel-based.js?<?=uniqid()?>"></script>
<script src="/dpm/dtoconfigurator/assets/js/dto-assembly-hours/station-based.js?<?=uniqid()?>"></script>
</body>
</html>